version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: diet-backend
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///diet.db
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
      - ./app.py:/app/app.py
    networks:
      - diet-network

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend.Dockerfile
  #   container_name: diet-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - diet-network

networks:
  diet-network:
    driver: bridge

volumes:
  data:
